name: Automated CI for Pull Requests

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'nsysu_selector_helper/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: 'nsysu_selector_helper/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: nsysu_selector_helper/

      - name: TypeScript type check
        run: yarn tsc -b --noEmit
        working-directory: nsysu_selector_helper/

      - name: Run tests
        run: yarn test --coverage --watchAll=false
        working-directory: nsysu_selector_helper/

      - name: Build
        run: yarn build
        working-directory: nsysu_selector_helper/
